<a href="https://colab.research.google.com/github/PreetiRonghe/Datascience/blob/main/Datatype_StructureandNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
x=10
y=12
if(x>y):
    print("x>y")
elif(x<y):
    print("x<y")
else:
    print("x=y")

x<y


In [7]:
numbers = range(1,6)
for i in numbers:
    print(i)

1
2
3
4
5


In [18]:
stars = range(1,7)
for i in stars:
    print("*" * i)

*
**
***
****
*****
******


In [23]:
i=0
while (i<5):
    print(i)
    i=i+1

0
1
2
3
4


In [31]:
def addElements(a,b,c):
  return (a+b+c)
result= addElements (1,2,3)
print(result)



6


In [32]:
def multiplyElements(a,b,c):
  return (a*b*c)
result= multiplyElements (5,2,3)
print(result)


30


In [33]:
i=0
while (i<5):
    print(i,"*i")
    i=i+1

0 *i
1 *i
2 *i
3 *i
4 *i


In [163]:
def addElements(a,b,c):
  return (a+b+c)
result= addElements ("dontbuy","thing","!")
print(result)

def addElements(a, b, c):
  return (a+b+c)
  a="hi!"
result= addElements ("","dontbuy","anything")
print(result)

def addElements(a="HiHello!",b,c):
  return (a+b+c)
result= addElements("","dontbuy","anything")
print(result)

SyntaxError: non-default argument follows default argument (ipython-input-163-1333557864.py, line 12)

In [75]:
batsmen =['Rohit','shikar',5,'Virat','pandya',10.5]
batsmen
type(batsmen)
# indexing always starts from Zero
batsmen[0]
#this returns elements starting from 0 and then 2 elements
batsmen[0:2]
#returns lenght of batsmen
len(batsmen)

6

In [139]:
bowlers =['Bumbhra','jadeja','chahal']
len(bowlers)
# Insert 'cherry' at index 1
#my_list.insert(1, 'cherry')
bowlers.insert(1,'kuldeep')
bowlers
# Fix: Use append to add an element to the end of the list
bowlers.append('kumble')
team=batsmen+bowlers
print(team)

['Rohit', 'shikar', 5, 'Virat', 'pandya', 10.5, 'Bumbhra', 'kuldeep', 'jadeja', 'chahal', 'kumble']


In [77]:
'Rohit' in bowlers
'Rohit' in team

True

In [78]:
odiDebut= ('Kohli',2008)
odiDebut[0]
odiDebut[1]=2009

TypeError: 'tuple' object does not support item assignment

In [79]:
setOfNumbers={4,5,3,1,9,10}
type(setOfNumbers)
print(setOfNumbers)
setOfNumbers_1={4,5,3,1,9,7,8,10,10}
print(setOfNumbers_1)
setOfNumbers.union(setOfNumbers_1)
setOfNumbers.intersection(setOfNumbers_1)
setOfNumbers.difference(setOfNumbers_1)
setOfNumbers_1.difference(setOfNumbers)

{1, 3, 4, 5, 9, 10}
{1, 3, 4, 5, 7, 8, 9, 10}


{7, 8}

In [133]:
studentsClass={1:"Preeti",
               10:"Fatima",
               2:"Shrilu",
               3:"Himnagi",
               4:"Lakshya",
               6:"Manish",
               7:"Nitin",
               8:"Shruti"}
type(studentsClass)
studentsClass.keys
studentsClass.keys()
studentsClass.values()
studentsClass[3]
studentsClass[9]

KeyError: 9

In [85]:
#this will return the last element
batsmen[-1]

10.5

In [92]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,0,11])
type(a)

numpy.ndarray

In [90]:
a.shape

(11,)

In [91]:
a.size

11

In [96]:
b = np.array([[1,2,3,4,5,6],[7,8,9,0,11,8]])

In [98]:
type(b)

numpy.ndarray

In [100]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 11,  8]])

In [102]:
b.size

12

In [106]:
b.shape

(2, 6)

In [107]:
b[0]

array([1, 2, 3, 4, 5, 6])

In [109]:
b[0][0]

np.int64(1)

In [112]:
#Row-->6;Column-->2
c=b.reshape(6,2)

In [114]:
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9,  0],
       [11,  8]])

In [123]:
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.prod())

56
0
11
5.090909090909091
0


In [119]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 11,  8]])

In [121]:
#gives sum of row values
b.sum(axis=0)

array([ 8, 10, 12,  4, 16, 14])

In [124]:
#gives columns sum values
b.sum(axis=1)

array([21, 43])

In [131]:
import math
num =16
sqrt_num =math.sqrt(num)
print(sqrt_num)
a=6.5
floor_num =math.floor(a)
print(floor_num)
ceil_num=math.ceil(a)
print(ceil_num)
b=4
# Corrected function name: math.factorial()
num_fact =math.factorial(b)
print(num_fact)

4.0
6
7
24
