<a href="https://colab.research.google.com/github/PreetiRonghe/Datascience/blob/main/Day09Python_Libraries_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np

In [20]:
ddup=pd.DataFrame({"Name":['A','A','B','B','C','D','E'],"Count":[1,2,2,3,4,3,4]})

In [21]:
ddup

Name  Count
0    A      1
1    A      2
2    B      2
3    B      3
4    C      4
5    D      3
6    E      4

In [22]:
ddup.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [23]:
ddup.drop_duplicates(ignore_index=True,inplace=True)
ddup

Name  Count
0    A      1
1    A      2
2    B      2
3    B      3
4    C      4
5    D      3
6    E      4

Rename the Column

In [24]:
ddup.rename(columns={"Name":"First Name","Count":"Num"},inplace=True)
ddup

First Name  Num
0          A    1
1          A    2
2          B    2
3          B    3
4          C    4
5          D    3
6          E    4

Connecting Dataframes

In [25]:
df1=pd.DataFrame([[1,2,3],[4,5,6]],columns=["A","B","C"])
df1

A  B  C
0  1  2  3
1  4  5  6

In [26]:
df2=pd.DataFrame([[7,8,9],[10,11,12]],columns=["A","B","C"])
df2

A   B   C
0   7   8   9
1  10  11  12

In [27]:
df3=pd.DataFrame([[1,2],[3,4]],columns=["C1","C2"])
df3

C1  C2
0   1   2
1   3   4

In [28]:
#Concat for Records
#join for column
pd.concat([df1,df2],axis=0,ignore_index=True)

A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [29]:
df1.join(df3)

A  B  C  C1  C2
0  1  2  3   1   2
1  4  5  6   3   4

In [30]:
#merging
d1=pd.DataFrame({"MovieID":[1,2,3,4,5],"Name":["Pathan","Jawan","Uri","Army","Don"]})
d1

MovieID    Name
0        1  Pathan
1        2   Jawan
2        3     Uri
3        4    Army
4        5     Don

In [31]:
d2=pd.DataFrame({"MovieID":[1,3,4,5,6],"Rating":[3,4,5,3,2], "Member":['Amir','Salman','Ajay','Vicky','Ranbir']})
d2

MovieID  Rating  Member
0        1       3    Amir
1        3       4  Salman
2        4       5    Ajay
3        5       3   Vicky
4        6       2  Ranbir

In [32]:
#merge
pd.merge(d1,d2,on="MovieID",how="left")


MovieID    Name  Rating  Member
0        1  Pathan     3.0    Amir
1        2   Jawan     NaN     NaN
2        3     Uri     4.0  Salman
3        4    Army     5.0    Ajay
4        5     Don     3.0   Vicky

In [33]:
pd.merge(d1,d2,on="MovieID",how="right")

MovieID    Name  Rating  Member
0        1  Pathan       3    Amir
1        3     Uri       4  Salman
2        4    Army       5    Ajay
3        5     Don       3   Vicky
4        6     NaN       2  Ranbir

In [34]:
pd.merge(d1,d2,on="MovieID",how="inner")

MovieID    Name  Rating  Member
0        1  Pathan       3    Amir
1        3     Uri       4  Salman
2        4    Army       5    Ajay
3        5     Don       3   Vicky

In [35]:
pd.merge(d1,d2,on="MovieID",how="outer")

MovieID    Name  Rating  Member
0        1  Pathan     3.0    Amir
1        2   Jawan     NaN     NaN
2        3     Uri     4.0  Salman
3        4    Army     5.0    Ajay
4        5     Don     3.0   Vicky
5        6     NaN     2.0  Ranbir

In [36]:
#Sorting
import pandas as pd
import numpy as np
sal=pd.read_csv("Salaries.csv")
sal

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [37]:
sal.head(10)

rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [38]:
sal.sort_values('salary')

rank discipline  phd  service     sex  salary
9        Prof          A   51       51    Male   57800
54  AssocProf          A   25       22  Female   62884
66   AsstProf          A    7        6  Female   63100
71  AssocProf          B   12        9  Female   71065
55   AsstProf          A    2        0  Female   72500
..        ...        ...  ...      ...     ...     ...
31       Prof          B   22       21    Male  155750
27       Prof          A   45       43    Male  155865
72       Prof          B   24       15  Female  161101
13       Prof          B   35       33    Male  162200
0        Prof          B   56       49    Male  186960

[78 rows x 6 columns]

In [39]:
sal.sort_values(by="salary",ascending=False)

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
13       Prof          B   35       33    Male  162200
72       Prof          B   24       15  Female  161101
27       Prof          A   45       43    Male  155865
31       Prof          B   22       21    Male  155750
..        ...        ...  ...      ...     ...     ...
55   AsstProf          A    2        0  Female   72500
71  AssocProf          B   12        9  Female   71065
66   AsstProf          A    7        6  Female   63100
54  AssocProf          A   25       22  Female   62884
9        Prof          A   51       51    Male   57800

[78 rows x 6 columns]

Lambda Function : A Lambda Function is an anonymous function without nameand is used for short and simple operation


1.   Suppose we want to a function which will look at the years of experience
2. If it is more than 20 years we will say "very Experienced and if Less than 20 years, will say less experienced




In [40]:
fn=lambda x:'Experience' if x>20 else 'Less Experienced'

In [41]:
fn(10)

'Less Experienced'

In [42]:
sal['service'].apply (lambda x: 'More Experiences' if x>20 else 'Less experience')

0     More Experiences
1      Less experience
2      Less experience
3     More Experiences
4      Less experience
            ...       
73     Less experience
74     Less experience
75     Less experience
76     Less experience
77     Less experience
Name: service, Length: 78, dtype: object

In [43]:
sal['status']=sal['service'].apply (lambda x: 'More Experiences' if x>20 else 'Less experience')
sal

rank discipline  phd  service     sex  salary            status
0        Prof          B   56       49    Male  186960  More Experiences
1        Prof          A   12        6    Male   93000   Less experience
2        Prof          A   23       20    Male  110515   Less experience
3        Prof          A   40       31    Male  131205  More Experiences
4        Prof          B   20       18    Male  104800   Less experience
..        ...        ...  ...      ...     ...     ...               ...
73       Prof          B   18       10  Female  105450   Less experience
74  AssocProf          B   19        6  Female  104542   Less experience
75       Prof          B   17       17  Female  124312   Less experience
76       Prof          A   28       14  Female  109954   Less experience
77       Prof          A   23       15  Female  109646   Less experience

[78 rows x 7 columns]

Math Function

In [44]:
import math

In [45]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [46]:
math.pi

3.141592653589793

In [47]:
math.pow(10,2)

100.0

In [51]:
math.trunc(10.9)

10

In [52]:
round(10.5)

10

In [54]:
math.sqrt(9)

3.0

In [48]:
fn=lambda x: "Experienced" if x>20 else 'Less Experienced'

Numpy:Numeric Python

In [50]:
import numpy as np

In [55]:
list1=[11,12,45,67,88,91]
print(list1)

[11, 12, 45, 67, 88, 91]


In [56]:
#Converting List to array
arr1=np.array(list1)
print(arr1)

[11 12 45 67 88 91]


In [57]:
#2*2 List
list2=[[1,2],[3,4]]
print(list2)
#creating array from list using NP function/library
arr2=np.array(list2)
print(arr2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [59]:
arr2.dtype

dtype('int64')

In [60]:
print(arr2.T)

[[1 3]
 [2 4]]


In [65]:
num1=np.array([1,2,3])
num2=np.array([4,5,6])
print(np.add(num1,num2))

[5 7 9]


In [66]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

Function Parameter

In [68]:
#positional Parameter for a funtion
def demo(name,age,location="Delhi"):
  print("name is",name)
  print("age is",age)
  print("location is",location)

In [69]:
demo("Preeti",40)

name is Preeti
age is 40
location is Delhi


In [70]:
demo("Preeti",40,"Mumbai")

name is Preeti
age is 40
location is Mumbai


In [72]:
#the function will take the sequence in which you pass the arguments
demo("Pune",34,"Preeti")

name is Pune
age is 34
location is Preeti


In [73]:
demo(location="Pune",age=34,name="Preeti")

name is Preeti
age is 34
location is Pune


In [74]:
#shuffle keywords
demo(age=34,location="Pune",name="Preeti")

name is Preeti
age is 34
location is Pune


In [76]:
demo(34,"Preeti")

name is 34
age is Preeti
location is Delhi


In [77]:
demo("Pune","Preeti",45)

name is Pune
age is Preeti
location is 45


Calendar

In [78]:
import calendar

In [79]:
dir(calendar)

['APRIL',
 'AUGUST',
 'Calendar',
 'DECEMBER',
 'Day',
 'EPOCH',
 'FEBRUARY',
 'FRIDAY',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'IntEnum',
 'JANUARY',
 'JULY',
 'JUNE',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MARCH',
 'MAY',
 'MONDAY',
 'Month',
 'NOVEMBER',
 'OCTOBER',
 'SATURDAY',
 'SEPTEMBER',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_get_default_locale',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 '_validate_month',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'global_enum',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 '

In [80]:
calendar.isleap(2020)

True

In [81]:
calendar.leapdays(2000,2022)

6

In [82]:
calendar.TextCalendar(firstweekday=0).prmonth(2022,11)

   November 2022
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30


In [85]:
calendar.calendar(2022)

'                                  2022\n\n      January                   February                   March\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                1  2          1  2  3  4  5  6          1  2  3  4  5  6\n 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13\n10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20\n17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27\n24 25 26 27 28 29 30      28                        28 29 30 31\n31\n\n       April                      May                       June\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n             1  2  3                         1             1  2  3  4  5\n 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12\n11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19\n18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26\n25 26 27 28 29

In [87]:
print("Calendar for year 2022 is as below:")
calendar.calendar(2022,2,1,6)
#year, w:width( vertical spacing),l:number of lines per week (horizontal spacing) ,c:sets the spacing between the month column
#m number of months that you want to display in each row

Calendar for year 2022 is as below:


'                                  2022\n\n      January                   February                   March\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                1  2          1  2  3  4  5  6          1  2  3  4  5  6\n 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13\n10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20\n17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27\n24 25 26 27 28 29 30      28                        28 29 30 31\n31\n\n       April                      May                       June\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n             1  2  3                         1             1  2  3  4  5\n 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12\n11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19\n18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26\n25 26 27 28 29

In [90]:
calendar.month(2025,11,1,1)

'   November 2025\nMo Tu We Th Fr Sa Su\n                1  2\n 3  4  5  6  7  8  9\n10 11 12 13 14 15 16\n17 18 19 20 21 22 23\n24 25 26 27 28 29 30\n'

In [91]:
calendar.monthcalendar(2022,7)

[[0, 0, 0, 0, 1, 2, 3],
 [4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30, 31]]

Datetime Module

In [94]:
from datetime import datetime

In [97]:
today = datetime.now().date()
print(today)

2025-11-19


In [98]:
#current date in different format
print(today.strftime("%d-%m-%Y"))

19-11-2025


In [99]:
print(today.strftime("%d-%b-%Y"))

19-Nov-2025


In [100]:
print(today.strftime("%d-%B-%Y"))

19-November-2025


In [101]:
print(today.strftime("%d-%B-%y"))

19-November-25


In [102]:
print(today.strftime("%d-%b-%y"))

19-Nov-25


In [103]:
print(today.strftime("%d/%b/%y"))

19/Nov/25


In [104]:
print(today.strftime("%b-%d-%y"))

Nov-19-25


In [108]:
#date diff
from datetime import date
date1 = date(2024, 6, 7)
date2 = date(2025, 3, 2)

In [109]:
diff=date2-date1
print(diff)

268 days, 0:00:00


In [112]:
x = datetime.now()
print(x)

2025-11-19 13:46:27.541084
