<a href="https://colab.research.google.com/github/PreetiRonghe/Datascience/blob/main/Dec15_Libraries_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - numerical python. When performing mathematical operations in numpy the processing is faster as list and data elements are stored in continuous locations
#Pandas- data manipulation
#Preprocessing of structured data-
#Series - 1 Column
#Dataframe - Multiple Columns
#Matplotlib - Visualization(EDA)  for data analysis
#pyplot has visualization methods
#so for visualization can we we use seaborn


In [13]:
import numpy as np
ar1=np.array([1,2,3,31,44,26])
print("The datatype of array",type(ar1))
print("==================")
print("The elements in array",ar1)
print("==================")
arr2=np.array([[1,2,3],[4,5,6]])
print("This is the actual array\n",arr2)
print("==================")
print("This will print the transpose of array\n",arr2.T)

The datatype of array <class 'numpy.ndarray'>
The elements in array [ 1  2  3 31 44 26]
This is the actual array
 [[1 2 3]
 [4 5 6]]
This will print the transpose of array
 [[1 4]
 [2 5]
 [3 6]]


In [11]:
print("Shape",ar1.shape)
print("==================")
print("Number of elements",ar1.size)
print("==================")
print("Data Type",ar1.dtype)
print("==================")
print("size of each element in Byte",ar1.itemsize)
print("==================")
print("Dimension",ar1.ndim)
print("==================")


Shape (6,)
Number of elements 6
Data Type int64
size of each element in Byte 8
Dimension 1


In [25]:
print("==================")
l1=[12,11,1,5,67,84,34]
t1=(23,51,16,52)
s1={12,11,1,5,67,84,34}
print("==================")
ar1=np.asarray(l1)
print("==================")
print(ar1)
ar2=np.asarray(t1)
print("==================")
print(ar2)
#ar3=np.asarray(l1+t1)
ar3=np.asarray(l1+list(t1))
ar5=np.asarray(l1+list(s1))
print("==================")
print("Appending list and tuple",ar3)
print("==================")
ar4=np.asarray(t1,dtype=float)
print(ar4)
print("==================")
print("Appending list and Tuple",ar5)

[12 11  1  5 67 84 34]
[23 51 16 52]
Appending list and tuple [12 11  1  5 67 84 34 23 51 16 52]
[23. 51. 16. 52.]
Appending list and Tuple [12 11  1  5 67 84 34  1 34 67 84  5 11 12]


In [18]:
#linspace
ar1=np.linspace(1,10,5)
print(ar1)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
arr=np.linspace(1,10,5,endpoint=False,dtype=int)
print(arr)

[1 2 4 6 8]


In [20]:
arr=np.linspace(1,10,5,endpoint=False)
print(arr)
#excludes 10 and the default type will be float

[1.  2.8 4.6 6.4 8.2]


In [21]:
#range
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [22]:
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [31]:
ar1=np.array([[1,3,6],[6,3,1]])
ar2=np.array([1,4,6])
print("Value of array 1\n",ar1)
print("Value of array 2\n",ar2)
print("==================")

print("Addition of aaray 1 and array 2")
print(np.add(ar1,ar2))
print("==================")

print("Subtraction")
print(np.subtract(ar1,ar2))
print("==================")

print("Multiplication")
print(np.multiply(ar1,ar2))
print("==================")

print("Division")
print(np.divide(ar1,ar2))
print("==================")

print("Log")
print(np.log(ar1))
print("==================")


print("Modulos / remainer")
print(np.mod(ar1,ar2))
print("==================")

print("EXPONENT / POWER")
print(np.power(ar1,ar2))
print("==================")

Value of array 1
 [[1 3 6]
 [6 3 1]]
Value of array 2
 [1 4 6]
Addition of aaray 1 and array 2
[[ 2  7 12]
 [ 7  7  7]]
Subtraction
[[ 0 -1  0]
 [ 5 -1 -5]]
Multiplication
[[ 1 12 36]
 [ 6 12  6]]
Division
[[1.         0.75       1.        ]
 [6.         0.75       0.16666667]]
Log
[[0.         1.09861229 1.79175947]
 [1.79175947 1.09861229 0.        ]]
Modulos / remainer
[[0 3 0]
 [0 3 1]]
EXPONENT / POWER
[[    1    81 46656]
 [    6    81     1]]
